version: '3.8'

services:
  # Project integrations: PostgreSQL instance for development purpose.
  postgresql:
    image: postgres:12.6
    environment:
      - POSTGRES_DB=monitoring
      - POSTGRES_USER=monitoring
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432

  # Project integrations: Kafka Broker instance for development purpose.
  kafka:
    image: bitnami/kafka:2.7.0
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_MAX_REQUEST_SIZE=8000000
      - KAFKA_CFG_MESSAGE_MAX_BYTES=8000000
    depends_on:
      - zookeeper

  # Project integrations: Zookeeper instance required by Kafka for development purpose.
  zookeeper:
    image: bitnami/zookeeper:3.5.7
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Development tools: Kafka Monitor UI to facilitate monitoring Kafka.
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9002:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
    depends_on:
      - kafka
