management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: monitoring-demo
  cloud:
    function:
      definition: purchaseSupplier;purchaseProcessor;purchaseSink
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: localhost:9092
      function:
        bindings:
          purchaseSupplier-out-0: purchases.processor.input
          purchaseProcessor-in-0: purchases.processor.input
          purchaseProcessor-out-0: purchases.sink.input
          purchaseSink-in-0: purchases.sink.input

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true

  datasource:
    password: pass
    url: jdbc:postgresql://127.0.0.1:5432/monitoring
    username: monitoring