persistence:
  enabled: false

datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://10.1.0.117:9090 # Replace by the internal k8s service endpoint
        version: 1
        editable: true
        isDefault: true
      - name: Alertmanager
        uid: alertmanager
        type: alertmanager
        access: proxy
        orgId: 1
        url: http://10.1.0.118:9093 # Replace by the internal k8s service endpoint
        version: 1
        editable: true
