server:
  extraScrapeConfigs:
    - job_name: app
      scrape_interval: 1s
      static_configs:
        - targets: ['10.71.25.76:8080'] # Replace it by your host IP
          labels:
            group: app
      metrics_path: /actuator/prometheus
